[project]
name = "11px"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elevenlabs>=2.6.0",
    "fastapi>=0.115.14",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
    "requests>=2.31.0",
]
